#*********************************************************************************************************
#
#                                 北京翼辉信息技术有限公司
#
#                                   微型安全实时操作系统
#
#                                       MS-RTOS(TM)
#
#                               Copyright All Rights Reserved
#
#--------------文件信息--------------------------------------------------------------------------------
#
# 文   件   名: libawtk.mk
#
# 创   建   人: IoT Studio
#
# 文件创建日期: 2016 年 10 月 08 日
#
# 描        述: 本文件由 IoT Studio 生成，用于配置 Makefile 功能，请勿手动修改
#*********************************************************************************************************

#*********************************************************************************************************
# Clear setting
#*********************************************************************************************************
include $(CLEAR_VARS_MK)

#*********************************************************************************************************
# Target
#*********************************************************************************************************
LOCAL_TARGET_NAME := libawtk.a

#*********************************************************************************************************
# Source list
#*********************************************************************************************************
LOCAL_SRCS := \
src/awtk/3rd/agg/src/agg_color_rgba.cpp \
src/awtk/3rd/agg/src/agg_image_filters.cpp \
src/awtk/3rd/agg/src/agg_sqrt_tables.cpp \
src/awtk/3rd/agg/src/agg_trans_affine.cpp \
src/awtk/3rd/agg/src/agg_vcgen_stroke.cpp \
src/awtk/3rd/agge/agge/math.cpp \
src/awtk/3rd/agge/agge/stroke.cpp \
src/awtk/3rd/agge/agge/stroke_features.cpp \
src/awtk/3rd/agge/agge/vector_rasterizer.cpp \
src/awtk/3rd/cairo/cairo/cairo-analysis-surface.c \
src/awtk/3rd/cairo/cairo/cairo-arc.c \
src/awtk/3rd/cairo/cairo/cairo-array.c \
src/awtk/3rd/cairo/cairo/cairo-atomic.c \
src/awtk/3rd/cairo/cairo/cairo-base64-stream.c \
src/awtk/3rd/cairo/cairo/cairo-base85-stream.c \
src/awtk/3rd/cairo/cairo/cairo-bentley-ottmann-rectangular.c \
src/awtk/3rd/cairo/cairo/cairo-bentley-ottmann-rectilinear.c \
src/awtk/3rd/cairo/cairo/cairo-bentley-ottmann.c \
src/awtk/3rd/cairo/cairo/cairo-botor-scan-converter.c \
src/awtk/3rd/cairo/cairo/cairo-boxes-intersect.c \
src/awtk/3rd/cairo/cairo/cairo-boxes.c \
src/awtk/3rd/cairo/cairo/cairo-cache.c \
src/awtk/3rd/cairo/cairo/cairo-clip-boxes.c \
src/awtk/3rd/cairo/cairo/cairo-clip-polygon.c \
src/awtk/3rd/cairo/cairo/cairo-clip-region.c \
src/awtk/3rd/cairo/cairo/cairo-clip-surface.c \
src/awtk/3rd/cairo/cairo/cairo-clip-tor-scan-converter.c \
src/awtk/3rd/cairo/cairo/cairo-clip.c \
src/awtk/3rd/cairo/cairo/cairo-color.c \
src/awtk/3rd/cairo/cairo/cairo-composite-rectangles.c \
src/awtk/3rd/cairo/cairo/cairo-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-contour.c \
src/awtk/3rd/cairo/cairo/cairo-damage.c \
src/awtk/3rd/cairo/cairo/cairo-debug.c \
src/awtk/3rd/cairo/cairo/cairo-default-context.c \
src/awtk/3rd/cairo/cairo/cairo-device.c \
src/awtk/3rd/cairo/cairo/cairo-error.c \
src/awtk/3rd/cairo/cairo/cairo-fallback-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-font-face-twin-data.c \
src/awtk/3rd/cairo/cairo/cairo-font-face-twin.c \
src/awtk/3rd/cairo/cairo/cairo-font-face.c \
src/awtk/3rd/cairo/cairo/cairo-font-options.c \
src/awtk/3rd/cairo/cairo/cairo-freelist.c \
src/awtk/3rd/cairo/cairo/cairo-gstate.c \
src/awtk/3rd/cairo/cairo/cairo-hash.c \
src/awtk/3rd/cairo/cairo/cairo-hull.c \
src/awtk/3rd/cairo/cairo/cairo-image-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-image-info.c \
src/awtk/3rd/cairo/cairo/cairo-image-source.c \
src/awtk/3rd/cairo/cairo/cairo-image-surface.c \
src/awtk/3rd/cairo/cairo/cairo-line.c \
src/awtk/3rd/cairo/cairo/cairo-lzw.c \
src/awtk/3rd/cairo/cairo/cairo-mask-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-matrix.c \
src/awtk/3rd/cairo/cairo/cairo-mempool.c \
src/awtk/3rd/cairo/cairo/cairo-mesh-pattern-rasterizer.c \
src/awtk/3rd/cairo/cairo/cairo-misc.c \
src/awtk/3rd/cairo/cairo/cairo-mono-scan-converter.c \
src/awtk/3rd/cairo/cairo/cairo-mutex.c \
src/awtk/3rd/cairo/cairo/cairo-no-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-observer.c \
src/awtk/3rd/cairo/cairo/cairo-output-stream.c \
src/awtk/3rd/cairo/cairo/cairo-paginated-surface.c \
src/awtk/3rd/cairo/cairo/cairo-path-bounds.c \
src/awtk/3rd/cairo/cairo/cairo-path-fill.c \
src/awtk/3rd/cairo/cairo/cairo-path-fixed.c \
src/awtk/3rd/cairo/cairo/cairo-path-in-fill.c \
src/awtk/3rd/cairo/cairo/cairo-path-stroke-boxes.c \
src/awtk/3rd/cairo/cairo/cairo-path-stroke-polygon.c \
src/awtk/3rd/cairo/cairo/cairo-path-stroke-traps.c \
src/awtk/3rd/cairo/cairo/cairo-path-stroke-tristrip.c \
src/awtk/3rd/cairo/cairo/cairo-path-stroke.c \
src/awtk/3rd/cairo/cairo/cairo-path.c \
src/awtk/3rd/cairo/cairo/cairo-pattern.c \
src/awtk/3rd/cairo/cairo/cairo-pen.c \
src/awtk/3rd/cairo/cairo/cairo-polygon-intersect.c \
src/awtk/3rd/cairo/cairo/cairo-polygon-reduce.c \
src/awtk/3rd/cairo/cairo/cairo-polygon.c \
src/awtk/3rd/cairo/cairo/cairo-raster-source-pattern.c \
src/awtk/3rd/cairo/cairo/cairo-recording-surface.c \
src/awtk/3rd/cairo/cairo/cairo-rectangle.c \
src/awtk/3rd/cairo/cairo/cairo-rectangular-scan-converter.c \
src/awtk/3rd/cairo/cairo/cairo-region.c \
src/awtk/3rd/cairo/cairo/cairo-rtree.c \
src/awtk/3rd/cairo/cairo/cairo-scaled-font.c \
src/awtk/3rd/cairo/cairo/cairo-shape-mask-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-slope.c \
src/awtk/3rd/cairo/cairo/cairo-spans-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-spans.c \
src/awtk/3rd/cairo/cairo/cairo-spline.c \
src/awtk/3rd/cairo/cairo/cairo-stroke-dash.c \
src/awtk/3rd/cairo/cairo/cairo-stroke-style.c \
src/awtk/3rd/cairo/cairo/cairo-surface-clipper.c \
src/awtk/3rd/cairo/cairo/cairo-surface-fallback.c \
src/awtk/3rd/cairo/cairo/cairo-surface-offset.c \
src/awtk/3rd/cairo/cairo/cairo-surface-snapshot.c \
src/awtk/3rd/cairo/cairo/cairo-surface-subsurface.c \
src/awtk/3rd/cairo/cairo/cairo-surface-wrapper.c \
src/awtk/3rd/cairo/cairo/cairo-surface.c \
src/awtk/3rd/cairo/cairo/cairo-tor-scan-converter.c \
src/awtk/3rd/cairo/cairo/cairo-tor22-scan-converter.c \
src/awtk/3rd/cairo/cairo/cairo-toy-font-face.c \
src/awtk/3rd/cairo/cairo/cairo-traps-compositor.c \
src/awtk/3rd/cairo/cairo/cairo-traps.c \
src/awtk/3rd/cairo/cairo/cairo-tristrip.c \
src/awtk/3rd/cairo/cairo/cairo-unicode.c \
src/awtk/3rd/cairo/cairo/cairo-user-font.c \
src/awtk/3rd/cairo/cairo/cairo-version.c \
src/awtk/3rd/cairo/cairo/cairo-wideint.c \
src/awtk/3rd/cairo/cairo/cairo.c \
src/awtk/3rd/cairo/demos/stars.c \
src/awtk/3rd/cjson/cJSON.c \
src/awtk/3rd/cjson/cJSON_Utils.c \
src/awtk/3rd/glad/glad.c \
src/awtk/3rd/gpinyin/src/dictlist.cpp \
src/awtk/3rd/gpinyin/src/dicttrie.cpp \
src/awtk/3rd/gpinyin/src/lpicache.cpp \
src/awtk/3rd/gpinyin/src/matrixsearch.cpp \
src/awtk/3rd/gpinyin/src/mystdlib.cpp \
src/awtk/3rd/gpinyin/src/ngram.cpp \
src/awtk/3rd/gpinyin/src/pinyinime.cpp \
src/awtk/3rd/gpinyin/src/searchutility.cpp \
src/awtk/3rd/gpinyin/src/spellingtrie.cpp \
src/awtk/3rd/gpinyin/src/splparser.cpp \
src/awtk/3rd/gpinyin/src/utf16char.cpp \
src/awtk/3rd/gpinyin/tools/gpinyin_gen.cpp \
src/awtk/3rd/gpinyin/tools/src/dictbuilder.cpp \
src/awtk/3rd/gpinyin/tools/src/dictlist.cpp \
src/awtk/3rd/gpinyin/tools/src/dicttrie.cpp \
src/awtk/3rd/gpinyin/tools/src/lpicache.cpp \
src/awtk/3rd/gpinyin/tools/src/mystdlib.cpp \
src/awtk/3rd/gpinyin/tools/src/ngram.cpp \
src/awtk/3rd/gpinyin/tools/src/pinyinime.cpp \
src/awtk/3rd/gpinyin/tools/src/searchutility.cpp \
src/awtk/3rd/gpinyin/tools/src/spellingtable.cpp \
src/awtk/3rd/gpinyin/tools/src/spellingtrie.cpp \
src/awtk/3rd/gpinyin/tools/src/splparser.cpp \
src/awtk/3rd/gpinyin/tools/src/utf16char.cpp \
src/awtk/3rd/gpinyin/tools/src/utf16reader.cpp \
src/awtk/3rd/gtest/googlemock/src/gmock-all.cc \
src/awtk/3rd/gtest/googlemock/src/gmock-cardinalities.cc \
src/awtk/3rd/gtest/googlemock/src/gmock-internal-utils.cc \
src/awtk/3rd/gtest/googlemock/src/gmock-matchers.cc \
src/awtk/3rd/gtest/googlemock/src/gmock-spec-builders.cc \
src/awtk/3rd/gtest/googlemock/src/gmock.cc \
src/awtk/3rd/gtest/googlemock/src/gmock_main.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-actions_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-cardinalities_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-generated-actions_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-generated-function-mockers_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-generated-internal-utils_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-generated-matchers_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-internal-utils_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-matchers_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-more-actions_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-nice-strict_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-port_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock-spec-builders_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_all_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_ex_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_leak_test_.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_link2_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_link_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_output_test_.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_stress_test.cc \
src/awtk/3rd/gtest/googlemock/test/gmock_test.cc \
src/awtk/3rd/gtest/googletest/codegear/gtest_all.cc \
src/awtk/3rd/gtest/googletest/codegear/gtest_link.cc \
src/awtk/3rd/gtest/googletest/samples/sample1.cc \
src/awtk/3rd/gtest/googletest/samples/sample10_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample1_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample2.cc \
src/awtk/3rd/gtest/googletest/samples/sample2_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample3_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample4.cc \
src/awtk/3rd/gtest/googletest/samples/sample4_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample5_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample6_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample7_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample8_unittest.cc \
src/awtk/3rd/gtest/googletest/samples/sample9_unittest.cc \
src/awtk/3rd/gtest/googletest/src/gtest-all.cc \
src/awtk/3rd/gtest/googletest/src/gtest-death-test.cc \
src/awtk/3rd/gtest/googletest/src/gtest-filepath.cc \
src/awtk/3rd/gtest/googletest/src/gtest-port.cc \
src/awtk/3rd/gtest/googletest/src/gtest-printers.cc \
src/awtk/3rd/gtest/googletest/src/gtest-test-part.cc \
src/awtk/3rd/gtest/googletest/src/gtest-typed-test.cc \
src/awtk/3rd/gtest/googletest/src/gtest.cc \
src/awtk/3rd/gtest/googletest/src/gtest_main.cc \
src/awtk/3rd/gtest/googletest/test/gtest-death-test_ex_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-death-test_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-filepath_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-linked_ptr_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-listener_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-message_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-options_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-param-test2_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-param-test_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-port_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-printers_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-test-part_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-tuple_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-typed-test2_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-typed-test_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest-unittest-api_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_all_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_break_on_failure_unittest_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_catch_exceptions_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_color_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_environment_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_env_var_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_filter_unittest_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_help_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_list_tests_unittest_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_main_unittest.cc \
src/awtk/3rd/gtest/googletest/test/gtest_no_test_unittest.cc \
src/awtk/3rd/gtest/googletest/test/gtest_output_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_pred_impl_unittest.cc \
src/awtk/3rd/gtest/googletest/test/gtest_premature_exit_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_prod_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_repeat_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_shuffle_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_sole_header_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_stress_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_throw_on_failure_ex_test.cc \
src/awtk/3rd/gtest/googletest/test/gtest_throw_on_failure_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_uninitialized_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_unittest.cc \
src/awtk/3rd/gtest/googletest/test/gtest_xml_outfile1_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_xml_outfile2_test_.cc \
src/awtk/3rd/gtest/googletest/test/gtest_xml_output_unittest_.cc \
src/awtk/3rd/gtest/googletest/test/production.cc \
src/awtk/3rd/gtest/googletest/xcode/Samples/FrameworkSample/widget.cc \
src/awtk/3rd/gtest/googletest/xcode/Samples/FrameworkSample/widget_test.cc \
src/awtk/3rd/libunibreak/emojidef.c \
src/awtk/3rd/libunibreak/graphemebreak.c \
src/awtk/3rd/libunibreak/linebreak.c \
src/awtk/3rd/libunibreak/linebreakdata.c \
src/awtk/3rd/libunibreak/linebreakdef.c \
src/awtk/3rd/libunibreak/unibreakbase.c \
src/awtk/3rd/libunibreak/unibreakdef.c \
src/awtk/3rd/libunibreak/wordbreak.c \
src/awtk/3rd/lz4/lz4.c \
src/awtk/3rd/lz4/lz4frame.c \
src/awtk/3rd/lz4/lz4hc.c \
src/awtk/3rd/lz4/xxhash.c \
src/awtk/3rd/miniz/miniz.c \
src/awtk/3rd/miniz/miniz_tdef.c \
src/awtk/3rd/miniz/miniz_tinfl.c \
src/awtk/3rd/miniz/miniz_zip.c \
src/awtk/3rd/nanovg/agg/nanovg_agg.cpp \
src/awtk/3rd/nanovg/agge/nanovg_agge.cpp \
src/awtk/3rd/nanovg/agge/nanovg_vertex.cpp \
src/awtk/3rd/nanovg/base/nanovg.c \
src/awtk/3rd/nanovg/bgfx/nanovg_bgfx.cpp \
src/awtk/3rd/nanovg/bgfx/nanovg_bgfx_ex.cpp \
src/awtk/3rd/nanovg/demos/agge_draw_image.c \
src/awtk/3rd/nanovg/demos/agge_fill.c \
src/awtk/3rd/nanovg/demos/agge_stroke.c \
src/awtk/3rd/nanovg/demos/agg_draw_image.c \
src/awtk/3rd/nanovg/demos/agg_fill.c \
src/awtk/3rd/nanovg/demos/agg_stroke.c \
src/awtk/3rd/nanovg/demos/bgfx_sdl_draw_image.cpp \
src/awtk/3rd/nanovg/demos/bgfx_sdl_draw_text.cpp \
src/awtk/3rd/nanovg/demos/bgfx_sdl_fill.cpp \
src/awtk/3rd/nanovg/demos/bgfx_sdl_stroke.cpp \
src/awtk/3rd/pixman/pixman/pixman-access-accessors.c \
src/awtk/3rd/pixman/pixman/pixman-access.c \
src/awtk/3rd/pixman/pixman/pixman-arm-detect-win32.asm \
src/awtk/3rd/pixman/pixman/pixman-arm-neon-asm-bilinear.S \
src/awtk/3rd/pixman/pixman/pixman-arm-neon-asm.S \
src/awtk/3rd/pixman/pixman/pixman-arm-neon.c \
src/awtk/3rd/pixman/pixman/pixman-arm-simd-asm-scaled.S \
src/awtk/3rd/pixman/pixman/pixman-arm-simd-asm.S \
src/awtk/3rd/pixman/pixman/pixman-arm-simd.c \
src/awtk/3rd/pixman/pixman/pixman-arm.c \
src/awtk/3rd/pixman/pixman/pixman-bits-image.c \
src/awtk/3rd/pixman/pixman/pixman-combine-float.c \
src/awtk/3rd/pixman/pixman/pixman-combine32.c \
src/awtk/3rd/pixman/pixman/pixman-conical-gradient.c \
src/awtk/3rd/pixman/pixman/pixman-edge-accessors.c \
src/awtk/3rd/pixman/pixman/pixman-edge.c \
src/awtk/3rd/pixman/pixman/pixman-fast-path.c \
src/awtk/3rd/pixman/pixman/pixman-filter.c \
src/awtk/3rd/pixman/pixman/pixman-general.c \
src/awtk/3rd/pixman/pixman/pixman-glyph.c \
src/awtk/3rd/pixman/pixman/pixman-gradient-walker.c \
src/awtk/3rd/pixman/pixman/pixman-image.c \
src/awtk/3rd/pixman/pixman/pixman-implementation.c \
src/awtk/3rd/pixman/pixman/pixman-linear-gradient.c \
src/awtk/3rd/pixman/pixman/pixman-matrix.c \
src/awtk/3rd/pixman/pixman/pixman-mips-dspr2-asm.S \
src/awtk/3rd/pixman/pixman/pixman-mips-dspr2.c \
src/awtk/3rd/pixman/pixman/pixman-mips-memcpy-asm.S \
src/awtk/3rd/pixman/pixman/pixman-mips.c \
src/awtk/3rd/pixman/pixman/pixman-mmx.c \
src/awtk/3rd/pixman/pixman/pixman-noop.c \
src/awtk/3rd/pixman/pixman/pixman-ppc.c \
src/awtk/3rd/pixman/pixman/pixman-radial-gradient.c \
src/awtk/3rd/pixman/pixman/pixman-region16.c \
src/awtk/3rd/pixman/pixman/pixman-region32.c \
src/awtk/3rd/pixman/pixman/pixman-solid-fill.c \
src/awtk/3rd/pixman/pixman/pixman-sse2.c \
src/awtk/3rd/pixman/pixman/pixman-ssse3.c \
src/awtk/3rd/pixman/pixman/pixman-timer.c \
src/awtk/3rd/pixman/pixman/pixman-trap.c \
src/awtk/3rd/pixman/pixman/pixman-utils.c \
src/awtk/3rd/pixman/pixman/pixman-vmx.c \
src/awtk/3rd/pixman/pixman/pixman-x86.c \
src/awtk/3rd/pixman/pixman/pixman.c \
src/awtk/3rd/SDL/gen/pointer-constraints-unstable-v1-protocol.c \
src/awtk/3rd/SDL/gen/relative-pointer-unstable-v1-protocol.c \
src/awtk/3rd/SDL/gen/wayland-protocol.c \
src/awtk/3rd/SDL/gen/xdg-shell-protocol.c \
src/awtk/3rd/SDL/gen/xdg-shell-unstable-v6-protocol.c \
src/awtk/3rd/SDL/src/atomic/SDL_atomic.c \
src/awtk/3rd/SDL/src/atomic/SDL_spinlock.c \
src/awtk/3rd/SDL/src/audio/alsa/SDL_alsa_audio.c \
src/awtk/3rd/SDL/src/audio/android/SDL_androidaudio.c \
src/awtk/3rd/SDL/src/audio/arts/SDL_artsaudio.c \
src/awtk/3rd/SDL/src/audio/directsound/SDL_directsound.c \
src/awtk/3rd/SDL/src/audio/disk/SDL_diskaudio.c \
src/awtk/3rd/SDL/src/audio/dsp/SDL_dspaudio.c \
src/awtk/3rd/SDL/src/audio/dummy/SDL_dummyaudio.c \
src/awtk/3rd/SDL/src/audio/emscripten/SDL_emscriptenaudio.c \
src/awtk/3rd/SDL/src/audio/esd/SDL_esdaudio.c \
src/awtk/3rd/SDL/src/audio/fusionsound/SDL_fsaudio.c \
src/awtk/3rd/SDL/src/audio/haiku/SDL_haikuaudio.cc \
src/awtk/3rd/SDL/src/audio/jack/SDL_jackaudio.c \
src/awtk/3rd/SDL/src/audio/nacl/SDL_naclaudio.c \
src/awtk/3rd/SDL/src/audio/nas/SDL_nasaudio.c \
src/awtk/3rd/SDL/src/audio/netbsd/SDL_netbsdaudio.c \
src/awtk/3rd/SDL/src/audio/paudio/SDL_paudio.c \
src/awtk/3rd/SDL/src/audio/psp/SDL_pspaudio.c \
src/awtk/3rd/SDL/src/audio/pulseaudio/SDL_pulseaudio.c \
src/awtk/3rd/SDL/src/audio/qsa/SDL_qsa_audio.c \
src/awtk/3rd/SDL/src/audio/SDL_audio.c \
src/awtk/3rd/SDL/src/audio/SDL_audiocvt.c \
src/awtk/3rd/SDL/src/audio/SDL_audiodev.c \
src/awtk/3rd/SDL/src/audio/SDL_audiotypecvt.c \
src/awtk/3rd/SDL/src/audio/SDL_mixer.c \
src/awtk/3rd/SDL/src/audio/SDL_wave.c \
src/awtk/3rd/SDL/src/audio/sndio/SDL_sndioaudio.c \
src/awtk/3rd/SDL/src/audio/sun/SDL_sunaudio.c \
src/awtk/3rd/SDL/src/audio/wasapi/SDL_wasapi.c \
src/awtk/3rd/SDL/src/audio/wasapi/SDL_wasapi_win32.c \
src/awtk/3rd/SDL/src/audio/wasapi/SDL_wasapi_winrt.cpp \
src/awtk/3rd/SDL/src/audio/winmm/SDL_winmm.c \
src/awtk/3rd/SDL/src/core/android/SDL_android.c \
src/awtk/3rd/SDL/src/core/linux/SDL_dbus.c \
src/awtk/3rd/SDL/src/core/linux/SDL_evdev.c \
src/awtk/3rd/SDL/src/core/linux/SDL_evdev_kbd.c \
src/awtk/3rd/SDL/src/core/linux/SDL_fcitx.c \
src/awtk/3rd/SDL/src/core/linux/SDL_ibus.c \
src/awtk/3rd/SDL/src/core/linux/SDL_ime.c \
src/awtk/3rd/SDL/src/core/linux/SDL_udev.c \
src/awtk/3rd/SDL/src/core/unix/SDL_poll.c \
src/awtk/3rd/SDL/src/core/windows/SDL_windows.c \
src/awtk/3rd/SDL/src/core/windows/SDL_xinput.c \
src/awtk/3rd/SDL/src/core/winrt/SDL_winrtapp_common.cpp \
src/awtk/3rd/SDL/src/core/winrt/SDL_winrtapp_direct3d.cpp \
src/awtk/3rd/SDL/src/core/winrt/SDL_winrtapp_xaml.cpp \
src/awtk/3rd/SDL/src/cpuinfo/SDL_cpuinfo.c \
src/awtk/3rd/SDL/src/dynapi/SDL_dynapi.c \
src/awtk/3rd/SDL/src/events/SDL_clipboardevents.c \
src/awtk/3rd/SDL/src/events/SDL_displayevents.c \
src/awtk/3rd/SDL/src/events/SDL_dropevents.c \
src/awtk/3rd/SDL/src/events/SDL_events.c \
src/awtk/3rd/SDL/src/events/SDL_gesture.c \
src/awtk/3rd/SDL/src/events/SDL_keyboard.c \
src/awtk/3rd/SDL/src/events/SDL_mouse.c \
src/awtk/3rd/SDL/src/events/SDL_quit.c \
src/awtk/3rd/SDL/src/events/SDL_touch.c \
src/awtk/3rd/SDL/src/events/SDL_windowevents.c \
src/awtk/3rd/SDL/src/file/SDL_rwops.c \
src/awtk/3rd/SDL/src/filesystem/android/SDL_sysfilesystem.c \
src/awtk/3rd/SDL/src/filesystem/dummy/SDL_sysfilesystem.c \
src/awtk/3rd/SDL/src/filesystem/emscripten/SDL_sysfilesystem.c \
src/awtk/3rd/SDL/src/filesystem/haiku/SDL_sysfilesystem.cc \
src/awtk/3rd/SDL/src/filesystem/nacl/SDL_sysfilesystem.c \
src/awtk/3rd/SDL/src/filesystem/unix/SDL_sysfilesystem.c \
src/awtk/3rd/SDL/src/filesystem/windows/SDL_sysfilesystem.c \
src/awtk/3rd/SDL/src/filesystem/winrt/SDL_sysfilesystem.cpp \
src/awtk/3rd/SDL/src/haptic/android/SDL_syshaptic.c \
src/awtk/3rd/SDL/src/haptic/darwin/SDL_syshaptic.c \
src/awtk/3rd/SDL/src/haptic/dummy/SDL_syshaptic.c \
src/awtk/3rd/SDL/src/haptic/linux/SDL_syshaptic.c \
src/awtk/3rd/SDL/src/haptic/SDL_haptic.c \
src/awtk/3rd/SDL/src/haptic/windows/SDL_dinputhaptic.c \
src/awtk/3rd/SDL/src/haptic/windows/SDL_windowshaptic.c \
src/awtk/3rd/SDL/src/haptic/windows/SDL_xinputhaptic.c \
src/awtk/3rd/SDL/src/hidapi/android/hid.cpp \
src/awtk/3rd/SDL/src/hidapi/hidtest/hidtest.cpp \
src/awtk/3rd/SDL/src/hidapi/libusb/hid.c \
src/awtk/3rd/SDL/src/hidapi/libusb/hidusb.cpp \
src/awtk/3rd/SDL/src/hidapi/linux/hid.c \
src/awtk/3rd/SDL/src/hidapi/linux/hid.cpp \
src/awtk/3rd/SDL/src/hidapi/linux/hidraw.cpp \
src/awtk/3rd/SDL/src/hidapi/mac/hid.c \
src/awtk/3rd/SDL/src/hidapi/testgui/mac_support.cpp \
src/awtk/3rd/SDL/src/hidapi/testgui/test.cpp \
src/awtk/3rd/SDL/src/hidapi/windows/hid.c \
src/awtk/3rd/SDL/src/joystick/android/SDL_sysjoystick.c \
src/awtk/3rd/SDL/src/joystick/bsd/SDL_sysjoystick.c \
src/awtk/3rd/SDL/src/joystick/darwin/SDL_sysjoystick.c \
src/awtk/3rd/SDL/src/joystick/dummy/SDL_sysjoystick.c \
src/awtk/3rd/SDL/src/joystick/emscripten/SDL_sysjoystick.c \
src/awtk/3rd/SDL/src/joystick/haiku/SDL_haikujoystick.cc \
src/awtk/3rd/SDL/src/joystick/hidapi/SDL_hidapijoystick.c \
src/awtk/3rd/SDL/src/joystick/hidapi/SDL_hidapi_ps4.c \
src/awtk/3rd/SDL/src/joystick/hidapi/SDL_hidapi_switch.c \
src/awtk/3rd/SDL/src/joystick/hidapi/SDL_hidapi_xbox360.c \
src/awtk/3rd/SDL/src/joystick/hidapi/SDL_hidapi_xboxone.c \
src/awtk/3rd/SDL/src/joystick/linux/SDL_sysjoystick.c \
src/awtk/3rd/SDL/src/joystick/psp/SDL_sysjoystick.c \
src/awtk/3rd/SDL/src/joystick/SDL_gamecontroller.c \
src/awtk/3rd/SDL/src/joystick/SDL_joystick.c \
src/awtk/3rd/SDL/src/joystick/steam/SDL_steamcontroller.c \
src/awtk/3rd/SDL/src/joystick/windows/SDL_dinputjoystick.c \
src/awtk/3rd/SDL/src/joystick/windows/SDL_mmjoystick.c \
src/awtk/3rd/SDL/src/joystick/windows/SDL_windowsjoystick.c \
src/awtk/3rd/SDL/src/joystick/windows/SDL_xinputjoystick.c \
src/awtk/3rd/SDL/src/libm/e_atan2.c \
src/awtk/3rd/SDL/src/libm/e_exp.c \
src/awtk/3rd/SDL/src/libm/e_fmod.c \
src/awtk/3rd/SDL/src/libm/e_log.c \
src/awtk/3rd/SDL/src/libm/e_log10.c \
src/awtk/3rd/SDL/src/libm/e_pow.c \
src/awtk/3rd/SDL/src/libm/e_rem_pio2.c \
src/awtk/3rd/SDL/src/libm/e_sqrt.c \
src/awtk/3rd/SDL/src/libm/k_cos.c \
src/awtk/3rd/SDL/src/libm/k_rem_pio2.c \
src/awtk/3rd/SDL/src/libm/k_sin.c \
src/awtk/3rd/SDL/src/libm/k_tan.c \
src/awtk/3rd/SDL/src/libm/s_atan.c \
src/awtk/3rd/SDL/src/libm/s_copysign.c \
src/awtk/3rd/SDL/src/libm/s_cos.c \
src/awtk/3rd/SDL/src/libm/s_fabs.c \
src/awtk/3rd/SDL/src/libm/s_floor.c \
src/awtk/3rd/SDL/src/libm/s_scalbn.c \
src/awtk/3rd/SDL/src/libm/s_sin.c \
src/awtk/3rd/SDL/src/libm/s_tan.c \
src/awtk/3rd/SDL/src/loadso/dlopen/SDL_sysloadso.c \
src/awtk/3rd/SDL/src/loadso/dummy/SDL_sysloadso.c \
src/awtk/3rd/SDL/src/loadso/windows/SDL_sysloadso.c \
src/awtk/3rd/SDL/src/main/android/SDL_android_main.c \
src/awtk/3rd/SDL/src/main/dummy/SDL_dummy_main.c \
src/awtk/3rd/SDL/src/main/haiku/SDL_BeApp.cc \
src/awtk/3rd/SDL/src/main/nacl/SDL_nacl_main.c \
src/awtk/3rd/SDL/src/main/psp/SDL_psp_main.c \
src/awtk/3rd/SDL/src/main/windows/SDL_windows_main.c \
src/awtk/3rd/SDL/src/main/winrt/SDL_winrt_main_NonXAML.cpp \
src/awtk/3rd/SDL/src/power/android/SDL_syspower.c \
src/awtk/3rd/SDL/src/power/emscripten/SDL_syspower.c \
src/awtk/3rd/SDL/src/power/haiku/SDL_syspower.c \
src/awtk/3rd/SDL/src/power/linux/SDL_syspower.c \
src/awtk/3rd/SDL/src/power/macosx/SDL_syspower.c \
src/awtk/3rd/SDL/src/power/psp/SDL_syspower.c \
src/awtk/3rd/SDL/src/power/SDL_power.c \
src/awtk/3rd/SDL/src/power/windows/SDL_syspower.c \
src/awtk/3rd/SDL/src/power/winrt/SDL_syspower.cpp \
src/awtk/3rd/SDL/src/render/direct3d/SDL_render_d3d.c \
src/awtk/3rd/SDL/src/render/direct3d/SDL_shaders_d3d.c \
src/awtk/3rd/SDL/src/render/direct3d11/SDL_render_d3d11.c \
src/awtk/3rd/SDL/src/render/direct3d11/SDL_render_winrt.cpp \
src/awtk/3rd/SDL/src/render/direct3d11/SDL_shaders_d3d11.c \
src/awtk/3rd/SDL/src/render/opengl/SDL_render_gl.c \
src/awtk/3rd/SDL/src/render/opengl/SDL_shaders_gl.c \
src/awtk/3rd/SDL/src/render/opengles/SDL_render_gles.c \
src/awtk/3rd/SDL/src/render/opengles2/SDL_render_gles2.c \
src/awtk/3rd/SDL/src/render/opengles2/SDL_shaders_gles2.c \
src/awtk/3rd/SDL/src/render/psp/SDL_render_psp.c \
src/awtk/3rd/SDL/src/render/SDL_d3dmath.c \
src/awtk/3rd/SDL/src/render/SDL_render.c \
src/awtk/3rd/SDL/src/render/SDL_yuv_sw.c \
src/awtk/3rd/SDL/src/render/software/SDL_blendfillrect.c \
src/awtk/3rd/SDL/src/render/software/SDL_blendline.c \
src/awtk/3rd/SDL/src/render/software/SDL_blendpoint.c \
src/awtk/3rd/SDL/src/render/software/SDL_drawline.c \
src/awtk/3rd/SDL/src/render/software/SDL_drawpoint.c \
src/awtk/3rd/SDL/src/render/software/SDL_render_sw.c \
src/awtk/3rd/SDL/src/render/software/SDL_rotate.c \
src/awtk/3rd/SDL/src/SDL.c \
src/awtk/3rd/SDL/src/SDL_assert.c \
src/awtk/3rd/SDL/src/SDL_dataqueue.c \
src/awtk/3rd/SDL/src/SDL_error.c \
src/awtk/3rd/SDL/src/SDL_hints.c \
src/awtk/3rd/SDL/src/SDL_log.c \
src/awtk/3rd/SDL/src/sensor/android/SDL_androidsensor.c \
src/awtk/3rd/SDL/src/sensor/dummy/SDL_dummysensor.c \
src/awtk/3rd/SDL/src/sensor/SDL_sensor.c \
src/awtk/3rd/SDL/src/stdlib/SDL_getenv.c \
src/awtk/3rd/SDL/src/stdlib/SDL_iconv.c \
src/awtk/3rd/SDL/src/stdlib/SDL_malloc.c \
src/awtk/3rd/SDL/src/stdlib/SDL_qsort.c \
src/awtk/3rd/SDL/src/stdlib/SDL_stdlib.c \
src/awtk/3rd/SDL/src/stdlib/SDL_string.c \
src/awtk/3rd/SDL/src/test/SDL_test_assert.c \
src/awtk/3rd/SDL/src/test/SDL_test_common.c \
src/awtk/3rd/SDL/src/test/SDL_test_compare.c \
src/awtk/3rd/SDL/src/test/SDL_test_crc32.c \
src/awtk/3rd/SDL/src/test/SDL_test_font.c \
src/awtk/3rd/SDL/src/test/SDL_test_fuzzer.c \
src/awtk/3rd/SDL/src/test/SDL_test_harness.c \
src/awtk/3rd/SDL/src/test/SDL_test_imageBlit.c \
src/awtk/3rd/SDL/src/test/SDL_test_imageBlitBlend.c \
src/awtk/3rd/SDL/src/test/SDL_test_imageFace.c \
src/awtk/3rd/SDL/src/test/SDL_test_imagePrimitives.c \
src/awtk/3rd/SDL/src/test/SDL_test_imagePrimitivesBlend.c \
src/awtk/3rd/SDL/src/test/SDL_test_log.c \
src/awtk/3rd/SDL/src/test/SDL_test_md5.c \
src/awtk/3rd/SDL/src/test/SDL_test_memory.c \
src/awtk/3rd/SDL/src/test/SDL_test_random.c \
src/awtk/3rd/SDL/src/thread/generic/SDL_syscond.c \
src/awtk/3rd/SDL/src/thread/generic/SDL_sysmutex.c \
src/awtk/3rd/SDL/src/thread/generic/SDL_syssem.c \
src/awtk/3rd/SDL/src/thread/generic/SDL_systhread.c \
src/awtk/3rd/SDL/src/thread/generic/SDL_systls.c \
src/awtk/3rd/SDL/src/thread/psp/SDL_syscond.c \
src/awtk/3rd/SDL/src/thread/psp/SDL_sysmutex.c \
src/awtk/3rd/SDL/src/thread/psp/SDL_syssem.c \
src/awtk/3rd/SDL/src/thread/psp/SDL_systhread.c \
src/awtk/3rd/SDL/src/thread/pthread/SDL_syscond.c \
src/awtk/3rd/SDL/src/thread/pthread/SDL_sysmutex.c \
src/awtk/3rd/SDL/src/thread/pthread/SDL_syssem.c \
src/awtk/3rd/SDL/src/thread/pthread/SDL_systhread.c \
src/awtk/3rd/SDL/src/thread/pthread/SDL_systls.c \
src/awtk/3rd/SDL/src/thread/SDL_thread.c \
src/awtk/3rd/SDL/src/thread/stdcpp/SDL_syscond.cpp \
src/awtk/3rd/SDL/src/thread/stdcpp/SDL_sysmutex.cpp \
src/awtk/3rd/SDL/src/thread/stdcpp/SDL_systhread.cpp \
src/awtk/3rd/SDL/src/thread/windows/SDL_sysmutex.c \
src/awtk/3rd/SDL/src/thread/windows/SDL_syssem.c \
src/awtk/3rd/SDL/src/thread/windows/SDL_systhread.c \
src/awtk/3rd/SDL/src/thread/windows/SDL_systls.c \
src/awtk/3rd/SDL/src/timer/dummy/SDL_systimer.c \
src/awtk/3rd/SDL/src/timer/haiku/SDL_systimer.c \
src/awtk/3rd/SDL/src/timer/psp/SDL_systimer.c \
src/awtk/3rd/SDL/src/timer/SDL_timer.c \
src/awtk/3rd/SDL/src/timer/unix/SDL_systimer.c \
src/awtk/3rd/SDL/src/timer/windows/SDL_systimer.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidclipboard.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidevents.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidgl.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidkeyboard.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidmessagebox.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidmouse.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidtouch.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidvideo.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidvulkan.c \
src/awtk/3rd/SDL/src/video/android/SDL_androidwindow.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_dyn.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_events.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_modes.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_mouse.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_opengl.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_render.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_shape.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_video.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_window.c \
src/awtk/3rd/SDL/src/video/directfb/SDL_DirectFB_WM.c \
src/awtk/3rd/SDL/src/video/dummy/SDL_nullevents.c \
src/awtk/3rd/SDL/src/video/dummy/SDL_nullframebuffer.c \
src/awtk/3rd/SDL/src/video/dummy/SDL_nullvideo.c \
src/awtk/3rd/SDL/src/video/emscripten/SDL_emscriptenevents.c \
src/awtk/3rd/SDL/src/video/emscripten/SDL_emscriptenframebuffer.c \
src/awtk/3rd/SDL/src/video/emscripten/SDL_emscriptenmouse.c \
src/awtk/3rd/SDL/src/video/emscripten/SDL_emscriptenopengles.c \
src/awtk/3rd/SDL/src/video/emscripten/SDL_emscriptenvideo.c \
src/awtk/3rd/SDL/src/video/haiku/SDL_bclipboard.cc \
src/awtk/3rd/SDL/src/video/haiku/SDL_bevents.cc \
src/awtk/3rd/SDL/src/video/haiku/SDL_bframebuffer.cc \
src/awtk/3rd/SDL/src/video/haiku/SDL_bkeyboard.cc \
src/awtk/3rd/SDL/src/video/haiku/SDL_bmodes.cc \
src/awtk/3rd/SDL/src/video/haiku/SDL_bopengl.cc \
src/awtk/3rd/SDL/src/video/haiku/SDL_bvideo.cc \
src/awtk/3rd/SDL/src/video/haiku/SDL_bwindow.cc \
src/awtk/3rd/SDL/src/video/kmsdrm/SDL_kmsdrmdyn.c \
src/awtk/3rd/SDL/src/video/kmsdrm/SDL_kmsdrmevents.c \
src/awtk/3rd/SDL/src/video/kmsdrm/SDL_kmsdrmmouse.c \
src/awtk/3rd/SDL/src/video/kmsdrm/SDL_kmsdrmopengles.c \
src/awtk/3rd/SDL/src/video/kmsdrm/SDL_kmsdrmvideo.c \
src/awtk/3rd/SDL/src/video/mir/SDL_mirdyn.c \
src/awtk/3rd/SDL/src/video/mir/SDL_mirevents.c \
src/awtk/3rd/SDL/src/video/mir/SDL_mirframebuffer.c \
src/awtk/3rd/SDL/src/video/mir/SDL_mirmouse.c \
src/awtk/3rd/SDL/src/video/mir/SDL_miropengl.c \
src/awtk/3rd/SDL/src/video/mir/SDL_mirvideo.c \
src/awtk/3rd/SDL/src/video/mir/SDL_mirvulkan.c \
src/awtk/3rd/SDL/src/video/mir/SDL_mirwindow.c \
src/awtk/3rd/SDL/src/video/nacl/SDL_naclevents.c \
src/awtk/3rd/SDL/src/video/nacl/SDL_naclglue.c \
src/awtk/3rd/SDL/src/video/nacl/SDL_naclopengles.c \
src/awtk/3rd/SDL/src/video/nacl/SDL_naclvideo.c \
src/awtk/3rd/SDL/src/video/nacl/SDL_naclwindow.c \
src/awtk/3rd/SDL/src/video/pandora/SDL_pandora.c \
src/awtk/3rd/SDL/src/video/pandora/SDL_pandora_events.c \
src/awtk/3rd/SDL/src/video/psp/SDL_pspevents.c \
src/awtk/3rd/SDL/src/video/psp/SDL_pspgl.c \
src/awtk/3rd/SDL/src/video/psp/SDL_pspmouse.c \
src/awtk/3rd/SDL/src/video/psp/SDL_pspvideo.c \
src/awtk/3rd/SDL/src/video/qnx/gl.c \
src/awtk/3rd/SDL/src/video/qnx/keyboard.c \
src/awtk/3rd/SDL/src/video/qnx/video.c \
src/awtk/3rd/SDL/src/video/raspberry/SDL_rpievents.c \
src/awtk/3rd/SDL/src/video/raspberry/SDL_rpimouse.c \
src/awtk/3rd/SDL/src/video/raspberry/SDL_rpiopengles.c \
src/awtk/3rd/SDL/src/video/raspberry/SDL_rpivideo.c \
src/awtk/3rd/SDL/src/video/SDL_blit.c \
src/awtk/3rd/SDL/src/video/SDL_blit_0.c \
src/awtk/3rd/SDL/src/video/SDL_blit_1.c \
src/awtk/3rd/SDL/src/video/SDL_blit_A.c \
src/awtk/3rd/SDL/src/video/SDL_blit_auto.c \
src/awtk/3rd/SDL/src/video/SDL_blit_copy.c \
src/awtk/3rd/SDL/src/video/SDL_blit_N.c \
src/awtk/3rd/SDL/src/video/SDL_blit_slow.c \
src/awtk/3rd/SDL/src/video/SDL_bmp.c \
src/awtk/3rd/SDL/src/video/SDL_clipboard.c \
src/awtk/3rd/SDL/src/video/SDL_egl.c \
src/awtk/3rd/SDL/src/video/SDL_fillrect.c \
src/awtk/3rd/SDL/src/video/SDL_pixels.c \
src/awtk/3rd/SDL/src/video/SDL_rect.c \
src/awtk/3rd/SDL/src/video/SDL_RLEaccel.c \
src/awtk/3rd/SDL/src/video/SDL_shape.c \
src/awtk/3rd/SDL/src/video/SDL_stretch.c \
src/awtk/3rd/SDL/src/video/SDL_surface.c \
src/awtk/3rd/SDL/src/video/SDL_video.c \
src/awtk/3rd/SDL/src/video/SDL_vulkan_utils.c \
src/awtk/3rd/SDL/src/video/SDL_yuv.c \
src/awtk/3rd/SDL/src/video/vivante/SDL_vivanteopengles.c \
src/awtk/3rd/SDL/src/video/vivante/SDL_vivanteplatform.c \
src/awtk/3rd/SDL/src/video/vivante/SDL_vivantevideo.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandclipboard.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylanddatamanager.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylanddyn.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandevents.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandmouse.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandopengles.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandtouch.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandvideo.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandvulkan.c \
src/awtk/3rd/SDL/src/video/wayland/SDL_waylandwindow.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsclipboard.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsevents.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsframebuffer.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowskeyboard.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsmessagebox.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsmodes.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsmouse.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsopengl.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsopengles.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsshape.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsvideo.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowsvulkan.c \
src/awtk/3rd/SDL/src/video/windows/SDL_windowswindow.c \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtevents.cpp \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtgamebar.cpp \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtkeyboard.cpp \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtmessagebox.cpp \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtmouse.cpp \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtopengles.cpp \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtpointerinput.cpp \
src/awtk/3rd/SDL/src/video/winrt/SDL_winrtvideo.cpp \
src/awtk/3rd/SDL/src/video/x11/edid-parse.c \
src/awtk/3rd/SDL/src/video/x11/imKStoUCS.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11clipboard.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11dyn.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11events.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11framebuffer.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11keyboard.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11messagebox.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11modes.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11mouse.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11opengl.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11opengles.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11shape.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11touch.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11video.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11vulkan.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11window.c \
src/awtk/3rd/SDL/src/video/x11/SDL_x11xinput2.c \
src/awtk/3rd/SDL/src/video/yuv2rgb/yuv_rgb.c \
src/awtk/3rd/SDL/test/checkkeys.c \
src/awtk/3rd/SDL/test/controllermap.c \
src/awtk/3rd/SDL/test/loopwave.c \
src/awtk/3rd/SDL/test/loopwavequeue.c \
src/awtk/3rd/SDL/test/testatomic.c \
src/awtk/3rd/SDL/test/testaudiocapture.c \
src/awtk/3rd/SDL/test/testaudiohotplug.c \
src/awtk/3rd/SDL/test/testaudioinfo.c \
src/awtk/3rd/SDL/test/testautomation.c \
src/awtk/3rd/SDL/test/testautomation_audio.c \
src/awtk/3rd/SDL/test/testautomation_clipboard.c \
src/awtk/3rd/SDL/test/testautomation_events.c \
src/awtk/3rd/SDL/test/testautomation_hints.c \
src/awtk/3rd/SDL/test/testautomation_keyboard.c \
src/awtk/3rd/SDL/test/testautomation_main.c \
src/awtk/3rd/SDL/test/testautomation_mouse.c \
src/awtk/3rd/SDL/test/testautomation_pixels.c \
src/awtk/3rd/SDL/test/testautomation_platform.c \
src/awtk/3rd/SDL/test/testautomation_rect.c \
src/awtk/3rd/SDL/test/testautomation_render.c \
src/awtk/3rd/SDL/test/testautomation_rwops.c \
src/awtk/3rd/SDL/test/testautomation_sdltest.c \
src/awtk/3rd/SDL/test/testautomation_stdlib.c \
src/awtk/3rd/SDL/test/testautomation_surface.c \
src/awtk/3rd/SDL/test/testautomation_syswm.c \
src/awtk/3rd/SDL/test/testautomation_timer.c \
src/awtk/3rd/SDL/test/testautomation_video.c \
src/awtk/3rd/SDL/test/testbounds.c \
src/awtk/3rd/SDL/test/testcustomcursor.c \
src/awtk/3rd/SDL/test/testdisplayinfo.c \
src/awtk/3rd/SDL/test/testdraw2.c \
src/awtk/3rd/SDL/test/testdrawchessboard.c \
src/awtk/3rd/SDL/test/testdropfile.c \
src/awtk/3rd/SDL/test/testerror.c \
src/awtk/3rd/SDL/test/testfile.c \
src/awtk/3rd/SDL/test/testfilesystem.c \
src/awtk/3rd/SDL/test/testgamecontroller.c \
src/awtk/3rd/SDL/test/testgesture.c \
src/awtk/3rd/SDL/test/testgl2.c \
src/awtk/3rd/SDL/test/testgles.c \
src/awtk/3rd/SDL/test/testgles2.c \
src/awtk/3rd/SDL/test/testhaptic.c \
src/awtk/3rd/SDL/test/testhittesting.c \
src/awtk/3rd/SDL/test/testhotplug.c \
src/awtk/3rd/SDL/test/testiconv.c \
src/awtk/3rd/SDL/test/testime.c \
src/awtk/3rd/SDL/test/testintersections.c \
src/awtk/3rd/SDL/test/testjoystick.c \
src/awtk/3rd/SDL/test/testkeys.c \
src/awtk/3rd/SDL/test/testloadso.c \
src/awtk/3rd/SDL/test/testlock.c \
src/awtk/3rd/SDL/test/testmessage.c \
src/awtk/3rd/SDL/test/testmultiaudio.c \
src/awtk/3rd/SDL/test/testnative.c \
src/awtk/3rd/SDL/test/testnativew32.c \
src/awtk/3rd/SDL/test/testnativex11.c \
src/awtk/3rd/SDL/test/testoverlay2.c \
src/awtk/3rd/SDL/test/testplatform.c \
src/awtk/3rd/SDL/test/testpower.c \
src/awtk/3rd/SDL/test/testqsort.c \
src/awtk/3rd/SDL/test/testrelative.c \
src/awtk/3rd/SDL/test/testrendercopyex.c \
src/awtk/3rd/SDL/test/testrendertarget.c \
src/awtk/3rd/SDL/test/testresample.c \
src/awtk/3rd/SDL/test/testrumble.c \
src/awtk/3rd/SDL/test/testscale.c \
src/awtk/3rd/SDL/test/testsem.c \
src/awtk/3rd/SDL/test/testsensor.c \
src/awtk/3rd/SDL/test/testshader.c \
src/awtk/3rd/SDL/test/testshape.c \
src/awtk/3rd/SDL/test/testsprite2.c \
src/awtk/3rd/SDL/test/testspriteminimal.c \
src/awtk/3rd/SDL/test/teststreaming.c \
src/awtk/3rd/SDL/test/testthread.c \
src/awtk/3rd/SDL/test/testtimer.c \
src/awtk/3rd/SDL/test/testver.c \
src/awtk/3rd/SDL/test/testviewport.c \
src/awtk/3rd/SDL/test/testvulkan.c \
src/awtk/3rd/SDL/test/testwm2.c \
src/awtk/3rd/SDL/test/testyuv.c \
src/awtk/3rd/SDL/test/testyuv_cvt.c \
src/awtk/3rd/SDL/test/torturethread.c \
src/awtk/3rd/SDL/visualtest/src/action_configparser.c \
src/awtk/3rd/SDL/visualtest/src/harness_argparser.c \
src/awtk/3rd/SDL/visualtest/src/linux/linux_process.c \
src/awtk/3rd/SDL/visualtest/src/mischelper.c \
src/awtk/3rd/SDL/visualtest/src/parsehelper.c \
src/awtk/3rd/SDL/visualtest/src/rwhelper.c \
src/awtk/3rd/SDL/visualtest/src/screenshot.c \
src/awtk/3rd/SDL/visualtest/src/sut_configparser.c \
src/awtk/3rd/SDL/visualtest/src/testharness.c \
src/awtk/3rd/SDL/visualtest/src/variators.c \
src/awtk/3rd/SDL/visualtest/src/variator_common.c \
src/awtk/3rd/SDL/visualtest/src/variator_exhaustive.c \
src/awtk/3rd/SDL/visualtest/src/variator_random.c \
src/awtk/3rd/SDL/visualtest/src/windows/windows_process.c \
src/awtk/3rd/SDL/visualtest/src/windows/windows_screenshot.c \
src/awtk/3rd/SDL/visualtest/unittest/testquit.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/accelerometer.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/common.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/fireworks.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/happy.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/keyboard.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/mixer.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/rectangles.c \
src/awtk/3rd/SDL/Xcode-iOS/Demos/src/touch.c \
src/awtk/3rd/SDL/Xcode-iOS/Template/SDL iOS Application/main.c \
src/awtk/demos/assets-1m.c \
src/awtk/demos/assets-mini.c \
src/awtk/demos/assets.c \
src/awtk/demos/assets_web.c \
src/awtk/demos/demo1_app.c \
src/awtk/demos/demo_animator_app.c \
src/awtk/demos/demo_basic.c \
src/awtk/demos/demo_desktop.c \
src/awtk/demos/demo_file_browser.c \
src/awtk/demos/demo_thread_app.c \
src/awtk/demos/demo_tr_app.c \
src/awtk/demos/demo_ui_app.c \
src/awtk/demos/demo_vg_app.c \
src/awtk/demos/preview_ui.c \
src/awtk/src/awtk_global.c \
src/awtk/src/base/assets_manager.c \
src/awtk/src/base/asset_loader.c \
src/awtk/src/base/asset_loader_default.c \
src/awtk/src/base/asset_loader_zip.c \
src/awtk/src/base/bitmap.c \
src/awtk/src/base/canvas.c \
src/awtk/src/base/children_layouter.c \
src/awtk/src/base/children_layouter_factory.c \
src/awtk/src/base/clip_board.c \
src/awtk/src/base/date_time_format.c \
src/awtk/src/base/dialog.c \
src/awtk/src/base/dialog_highlighter.c \
src/awtk/src/base/dialog_highlighter_factory.c \
src/awtk/src/base/enums.c \
src/awtk/src/base/events.c \
src/awtk/src/base/event_queue.c \
src/awtk/src/base/font.c \
src/awtk/src/base/font_loader.c \
src/awtk/src/base/font_manager.c \
src/awtk/src/base/glyph_cache.c \
src/awtk/src/base/graphic_buffer.c \
src/awtk/src/base/hscrollable.c \
src/awtk/src/base/idle.c \
src/awtk/src/base/image_base.c \
src/awtk/src/base/image_loader.c \
src/awtk/src/base/image_manager.c \
src/awtk/src/base/input_device_status.c \
src/awtk/src/base/input_engine.c \
src/awtk/src/base/input_method.c \
src/awtk/src/base/layout.c \
src/awtk/src/base/lcd.c \
src/awtk/src/base/lcd_profile.c \
src/awtk/src/base/line_break.c \
src/awtk/src/base/locale_info.c \
src/awtk/src/base/main_loop.c \
src/awtk/src/base/native_window.c \
src/awtk/src/base/self_layouter.c \
src/awtk/src/base/self_layouter_factory.c \
src/awtk/src/base/shortcut.c \
src/awtk/src/base/style.c \
src/awtk/src/base/style_const.c \
src/awtk/src/base/style_factory.c \
src/awtk/src/base/style_mutable.c \
src/awtk/src/base/suggest_words.c \
src/awtk/src/base/system_info.c \
src/awtk/src/base/text_edit.c \
src/awtk/src/base/theme.c \
src/awtk/src/base/timer.c \
src/awtk/src/base/ui_builder.c \
src/awtk/src/base/ui_feedback.c \
src/awtk/src/base/ui_loader.c \
src/awtk/src/base/velocity.c \
src/awtk/src/base/vgcanvas.c \
src/awtk/src/base/widget.c \
src/awtk/src/base/widget_animator.c \
src/awtk/src/base/widget_animator_factory_null.c \
src/awtk/src/base/widget_animator_manager.c \
src/awtk/src/base/widget_factory.c \
src/awtk/src/base/widget_vtable.c \
src/awtk/src/base/window.c \
src/awtk/src/base/window_animator.c \
src/awtk/src/base/window_animator_factory.c \
src/awtk/src/base/window_base.c \
src/awtk/src/base/window_manager.c \
src/awtk/src/blend/blend_image_bgr565_bgr565.c \
src/awtk/src/blend/blend_image_bgr565_bgra8888.c \
src/awtk/src/blend/blend_image_bgr565_rgba8888.c \
src/awtk/src/blend/blend_image_bgr888_bgr565.c \
src/awtk/src/blend/blend_image_bgr888_bgra8888.c \
src/awtk/src/blend/blend_image_bgr888_rgba8888.c \
src/awtk/src/blend/blend_image_bgra8888_bgr565.c \
src/awtk/src/blend/blend_image_bgra8888_bgra8888.c \
src/awtk/src/blend/blend_image_bgra8888_rgba8888.c \
src/awtk/src/blend/blend_image_rgb565_bgr565.c \
src/awtk/src/blend/blend_image_rgb565_bgra8888.c \
src/awtk/src/blend/blend_image_rgb565_rgba8888.c \
src/awtk/src/blend/blend_image_rgb888_bgr565.c \
src/awtk/src/blend/blend_image_rgb888_bgra8888.c \
src/awtk/src/blend/blend_image_rgb888_rgba8888.c \
src/awtk/src/blend/blend_image_rgba8888_bgr565.c \
src/awtk/src/blend/blend_image_rgba8888_bgra8888.c \
src/awtk/src/blend/blend_image_rgba8888_rgba8888.c \
src/awtk/src/blend/fill_image_abgr8888.c \
src/awtk/src/blend/fill_image_argb8888.c \
src/awtk/src/blend/fill_image_bgr565.c \
src/awtk/src/blend/fill_image_bgr888.c \
src/awtk/src/blend/fill_image_bgra8888.c \
src/awtk/src/blend/fill_image_rgb565.c \
src/awtk/src/blend/fill_image_rgb888.c \
src/awtk/src/blend/fill_image_rgba8888.c \
src/awtk/src/blend/image_g2d.c \
src/awtk/src/blend/rotate_image_bgr565.c \
src/awtk/src/blend/rotate_image_bgr888.c \
src/awtk/src/blend/rotate_image_bgra8888.c \
src/awtk/src/blend/rotate_image_rgb565.c \
src/awtk/src/blend/rotate_image_rgb888.c \
src/awtk/src/blend/rotate_image_rgba8888.c \
src/awtk/src/blend/soft_g2d.c \
src/awtk/src/blend/stm32_g2d.c \
src/awtk/src/clip_board/clip_board_default.c \
src/awtk/src/clip_board/clip_board_sdl.c \
src/awtk/src/compressors/compressor_miniz.c \
src/awtk/src/dialog_highlighters/dialog_highlighter_builtins.c \
src/awtk/src/dialog_highlighters/dialog_highlighter_default.c \
src/awtk/src/ext_widgets/canvas_widget/canvas_widget.c \
src/awtk/src/ext_widgets/color_picker/color_component.c \
src/awtk/src/ext_widgets/color_picker/color_picker.c \
src/awtk/src/ext_widgets/color_picker/rgb_and_hsv.c \
src/awtk/src/ext_widgets/combo_box_ex/combo_box_ex.c \
src/awtk/src/ext_widgets/ext_widgets.c \
src/awtk/src/ext_widgets/features/draggable.c \
src/awtk/src/ext_widgets/file_browser/file_browser.c \
src/awtk/src/ext_widgets/file_browser/file_browser_view.c \
src/awtk/src/ext_widgets/file_browser/file_chooser.c \
src/awtk/src/ext_widgets/gif_image/gif_image.c \
src/awtk/src/ext_widgets/guage/guage.c \
src/awtk/src/ext_widgets/guage/guage_pointer.c \
src/awtk/src/ext_widgets/image_animation/image_animation.c \
src/awtk/src/ext_widgets/image_value/image_value.c \
src/awtk/src/ext_widgets/keyboard/candidates.c \
src/awtk/src/ext_widgets/keyboard/keyboard.c \
src/awtk/src/ext_widgets/mledit/line_number.c \
src/awtk/src/ext_widgets/mledit/mledit.c \
src/awtk/src/ext_widgets/mutable_image/mutable_image.c \
src/awtk/src/ext_widgets/progress_circle/progress_circle.c \
src/awtk/src/ext_widgets/rich_text/rich_text.c \
src/awtk/src/ext_widgets/rich_text/rich_text_node.c \
src/awtk/src/ext_widgets/rich_text/rich_text_parser.c \
src/awtk/src/ext_widgets/rich_text/rich_text_render_node.c \
src/awtk/src/ext_widgets/scroll_label/hscroll_label.c \
src/awtk/src/ext_widgets/scroll_view/children_layouter_list_view.c \
src/awtk/src/ext_widgets/scroll_view/list_item.c \
src/awtk/src/ext_widgets/scroll_view/list_view.c \
src/awtk/src/ext_widgets/scroll_view/list_view_h.c \
src/awtk/src/ext_widgets/scroll_view/scroll_bar.c \
src/awtk/src/ext_widgets/scroll_view/scroll_view.c \
src/awtk/src/ext_widgets/slide_menu/slide_menu.c \
src/awtk/src/ext_widgets/slide_view/slide_indicator.c \
src/awtk/src/ext_widgets/slide_view/slide_view.c \
src/awtk/src/ext_widgets/svg_image/svg_image.c \
src/awtk/src/ext_widgets/switch/switch.c \
src/awtk/src/ext_widgets/text_selector/text_selector.c \
src/awtk/src/ext_widgets/time_clock/time_clock.c \
src/awtk/src/file_transfer/file_receiver.c \
src/awtk/src/file_transfer/file_sender.c \
src/awtk/src/file_transfer/tools/serial_file_receiver.c \
src/awtk/src/file_transfer/tools/serial_file_sender.c \
src/awtk/src/file_transfer/tools/tcp_file_receiver.c \
src/awtk/src/file_transfer/tools/tcp_file_sender.c \
src/awtk/src/font_loader/font_loader_bitmap.c \
src/awtk/src/font_loader/font_loader_ft.c \
src/awtk/src/font_loader/font_loader_stb.c \
src/awtk/src/graphic_buffer/graphic_buffer_default.c \
src/awtk/src/image_loader/image_loader_stb.c \
src/awtk/src/input_engines/input_engine_null.c \
src/awtk/src/input_engines/input_engine_pinyin.cpp \
src/awtk/src/input_methods/input_method_creator.c \
src/awtk/src/layouters/children_layouter_builtins.c \
src/awtk/src/layouters/children_layouter_default.c \
src/awtk/src/layouters/children_layouter_parser.c \
src/awtk/src/layouters/self_layouter_builtins.c \
src/awtk/src/layouters/self_layouter_default.c \
src/awtk/src/layouters/self_layouter_menu.c \
src/awtk/src/layouters/self_layouter_parser.c \
src/awtk/src/lcd/lcd_mem_bgr565.c \
src/awtk/src/lcd/lcd_mem_bgr888.c \
src/awtk/src/lcd/lcd_mem_bgra8888.c \
src/awtk/src/lcd/lcd_mem_rgb565.c \
src/awtk/src/lcd/lcd_mem_rgb888.c \
src/awtk/src/lcd/lcd_mem_rgba8888.c \
src/awtk/src/lcd/lcd_mem_special.c \
src/awtk/src/lcd/lcd_mono.c \
src/awtk/src/lcd/lcd_nanovg.c \
src/awtk/src/lcd/lcd_sdl2.c \
src/awtk/src/lcd/lcd_sdl2_mono.c \
src/awtk/src/main_loop/main_loop_dummy.c \
src/awtk/src/main_loop/main_loop_sdl.c \
src/awtk/src/main_loop/main_loop_simple.c \
src/awtk/src/misc/new.cpp \
src/awtk/src/misc/test_cpp.cpp \
src/awtk/src/native_window/native_window_fb_gl.c \
src/awtk/src/native_window/native_window_raw.c \
src/awtk/src/native_window/native_window_sdl.c \
src/awtk/src/platforms/cmsis_os/mutex.c \
src/awtk/src/platforms/cmsis_os/rtos.c \
src/awtk/src/platforms/cmsis_os/semaphore.c \
src/awtk/src/platforms/cmsis_os/sys_tick.c \
src/awtk/src/platforms/cmsis_os/thread.c \
src/awtk/src/platforms/common/sys_tick.c \
src/awtk/src/platforms/pc/dl.c \
src/awtk/src/platforms/pc/fs_os.c \
src/awtk/src/platforms/pc/platform.c \
src/awtk/src/platforms/pc/platform_time.c \
src/awtk/src/platforms/pc/thread_with_pthread.c \
src/awtk/src/platforms/pc/thread_with_sdl.c \
src/awtk/src/platforms/raw/cond_var_null.c \
src/awtk/src/platforms/raw/fs_os.c \
src/awtk/src/platforms/raw/mutex_null.c \
src/awtk/src/platforms/raw/sys_tick_handler.c \
src/awtk/src/platforms/rtt/mutex.c \
src/awtk/src/platforms/rtt/rtos.c \
src/awtk/src/platforms/rtt/semaphore.c \
src/awtk/src/platforms/rtt/thread.c \
src/awtk/src/platforms/tos/mutex.c \
src/awtk/src/platforms/tos/rtos.c \
src/awtk/src/platforms/tos/semaphore.c \
src/awtk/src/platforms/tos/thread.c \
src/awtk/src/streams/buffered/istream_buffered.c \
src/awtk/src/streams/buffered/ostream_buffered.c \
src/awtk/src/streams/file/istream_file.c \
src/awtk/src/streams/file/ostream_file.c \
src/awtk/src/streams/inet/iostream_tcp.c \
src/awtk/src/streams/inet/iostream_udp.c \
src/awtk/src/streams/inet/istream_tcp.c \
src/awtk/src/streams/inet/istream_udp.c \
src/awtk/src/streams/inet/ostream_tcp.c \
src/awtk/src/streams/inet/ostream_udp.c \
src/awtk/src/streams/mem/iostream_mem.c \
src/awtk/src/streams/mem/istream_mem.c \
src/awtk/src/streams/mem/ostream_mem.c \
src/awtk/src/streams/misc/ostream_retry.c \
src/awtk/src/streams/noisy/iostream_noisy.c \
src/awtk/src/streams/noisy/ostream_noisy.c \
src/awtk/src/streams/serial/iostream_serial.c \
src/awtk/src/streams/serial/istream_serial.c \
src/awtk/src/streams/serial/ostream_serial.c \
src/awtk/src/streams/serial/serial_helper.c \
src/awtk/src/streams/shdlc/iostream_shdlc.c \
src/awtk/src/streams/shdlc/istream_shdlc.c \
src/awtk/src/streams/shdlc/ostream_shdlc.c \
src/awtk/src/streams/shdlc/shdlc_helper.c \
src/awtk/src/streams/tools/serial_at.c \
src/awtk/src/streams/tools/serial_echo.c \
src/awtk/src/streams/tools/serial_send.c \
src/awtk/src/streams/tools/shdlc_recv.c \
src/awtk/src/streams/tools/shdlc_send.c \
src/awtk/src/streams/tools/udp_recv.c \
src/awtk/src/streams/tools/udp_send.c \
src/awtk/src/svg/bsvg.c \
src/awtk/src/svg/bsvg_builder.c \
src/awtk/src/svg/bsvg_draw.c \
src/awtk/src/svg/bsvg_to_svg.c \
src/awtk/src/svg/svg_path.c \
src/awtk/src/svg/svg_path_parser.c \
src/awtk/src/svg/svg_shape.c \
src/awtk/src/svg/svg_to_bsvg.c \
src/awtk/src/tkc/action_queue.c \
src/awtk/src/tkc/action_thread.c \
src/awtk/src/tkc/action_thread_pool.c \
src/awtk/src/tkc/asset_info.c \
src/awtk/src/tkc/async.c \
src/awtk/src/tkc/buffer.c \
src/awtk/src/tkc/color.c \
src/awtk/src/tkc/color_parser.c \
src/awtk/src/tkc/compressor.c \
src/awtk/src/tkc/cond_var.c \
src/awtk/src/tkc/crc.c \
src/awtk/src/tkc/darray.c \
src/awtk/src/tkc/data_reader.c \
src/awtk/src/tkc/data_reader_factory.c \
src/awtk/src/tkc/data_reader_file.c \
src/awtk/src/tkc/data_writer.c \
src/awtk/src/tkc/data_writer_factory.c \
src/awtk/src/tkc/data_writer_file.c \
src/awtk/src/tkc/date_time.c \
src/awtk/src/tkc/easing.c \
src/awtk/src/tkc/emitter.c \
src/awtk/src/tkc/event.c \
src/awtk/src/tkc/event_source.c \
src/awtk/src/tkc/event_source_fd.c \
src/awtk/src/tkc/event_source_idle.c \
src/awtk/src/tkc/event_source_manager.c \
src/awtk/src/tkc/event_source_manager_default.c \
src/awtk/src/tkc/event_source_timer.c \
src/awtk/src/tkc/expr_eval.c \
src/awtk/src/tkc/fs.c \
src/awtk/src/tkc/func_call_parser.c \
src/awtk/src/tkc/idle_info.c \
src/awtk/src/tkc/idle_manager.c \
src/awtk/src/tkc/int_str.c \
src/awtk/src/tkc/iostream.c \
src/awtk/src/tkc/istream.c \
src/awtk/src/tkc/log.c \
src/awtk/src/tkc/matrix.c \
src/awtk/src/tkc/mem.c \
src/awtk/src/tkc/named_value.c \
src/awtk/src/tkc/object.c \
src/awtk/src/tkc/object_array.c \
src/awtk/src/tkc/object_default.c \
src/awtk/src/tkc/ostream.c \
src/awtk/src/tkc/path.c \
src/awtk/src/tkc/qaction.c \
src/awtk/src/tkc/rect.c \
src/awtk/src/tkc/ring_buffer.c \
src/awtk/src/tkc/rom_fs.c \
src/awtk/src/tkc/slist.c \
src/awtk/src/tkc/socket_helper.c \
src/awtk/src/tkc/socket_pair.c \
src/awtk/src/tkc/str.c \
src/awtk/src/tkc/str_str.c \
src/awtk/src/tkc/timer_info.c \
src/awtk/src/tkc/timer_manager.c \
src/awtk/src/tkc/time_now.c \
src/awtk/src/tkc/tokenizer.c \
src/awtk/src/tkc/utf8.c \
src/awtk/src/tkc/utils.c \
src/awtk/src/tkc/value.c \
src/awtk/src/tkc/value_desc.c \
src/awtk/src/tkc/waitable_action_queue.c \
src/awtk/src/tkc/wstr.c \
src/awtk/src/ubjson/tools/ubjson_dump.c \
src/awtk/src/ubjson/ubjson_parser.c \
src/awtk/src/ubjson/ubjson_reader.c \
src/awtk/src/ubjson/ubjson_writer.c \
src/awtk/src/ui_loader/ui_binary_writer.c \
src/awtk/src/ui_loader/ui_builder_default.c \
src/awtk/src/ui_loader/ui_loader_default.c \
src/awtk/src/ui_loader/ui_loader_xml.c \
src/awtk/src/ui_loader/ui_serializer.c \
src/awtk/src/ui_loader/ui_xml_writer.c \
src/awtk/src/ui_loader/window_open.c \
src/awtk/src/vgcanvas/vgcanvas_cairo.c \
src/awtk/src/vgcanvas/vgcanvas_nanovg_bgfx.c \
src/awtk/src/vgcanvas/vgcanvas_nanovg_gl.c \
src/awtk/src/vgcanvas/vgcanvas_nanovg_soft.c \
src/awtk/src/vgcanvas/vgcanvas_null.c \
src/awtk/src/widgets/app_bar.c \
src/awtk/src/widgets/button.c \
src/awtk/src/widgets/button_group.c \
src/awtk/src/widgets/calibration_win.c \
src/awtk/src/widgets/check_button.c \
src/awtk/src/widgets/clip_view.c \
src/awtk/src/widgets/color_tile.c \
src/awtk/src/widgets/column.c \
src/awtk/src/widgets/combo_box.c \
src/awtk/src/widgets/combo_box_item.c \
src/awtk/src/widgets/dialog_client.c \
src/awtk/src/widgets/dialog_helper.c \
src/awtk/src/widgets/dialog_title.c \
src/awtk/src/widgets/digit_clock.c \
src/awtk/src/widgets/dragger.c \
src/awtk/src/widgets/edit.c \
src/awtk/src/widgets/grid.c \
src/awtk/src/widgets/grid_item.c \
src/awtk/src/widgets/group_box.c \
src/awtk/src/widgets/image.c \
src/awtk/src/widgets/label.c \
src/awtk/src/widgets/overlay.c \
src/awtk/src/widgets/pages.c \
src/awtk/src/widgets/popup.c \
src/awtk/src/widgets/progress_bar.c \
src/awtk/src/widgets/row.c \
src/awtk/src/widgets/slider.c \
src/awtk/src/widgets/spin_box.c \
src/awtk/src/widgets/system_bar.c \
src/awtk/src/widgets/tab_button.c \
src/awtk/src/widgets/tab_button_group.c \
src/awtk/src/widgets/tab_control.c \
src/awtk/src/widgets/view.c \
src/awtk/src/widgets/widgets.c \
src/awtk/src/widget_animators/widget_animator_factory.c \
src/awtk/src/widget_animators/widget_animator_prop.c \
src/awtk/src/widget_animators/widget_animator_prop2.c \
src/awtk/src/widget_animators/widget_animator_scroll.c \
src/awtk/src/window_animators/window_animator_builtins.c \
src/awtk/src/window_animators/window_animator_center_scale.c \
src/awtk/src/window_animators/window_animator_common.c \
src/awtk/src/window_animators/window_animator_fade.c \
src/awtk/src/window_animators/window_animator_htranslate.c \
src/awtk/src/window_animators/window_animator_popdown.c \
src/awtk/src/window_animators/window_animator_popup.c \
src/awtk/src/window_animators/window_animator_slide.c \
src/awtk/src/window_animators/window_animator_slide_down.c \
src/awtk/src/window_animators/window_animator_slide_left.c \
src/awtk/src/window_animators/window_animator_slide_right.c \
src/awtk/src/window_animators/window_animator_slide_up.c \
src/awtk/src/window_animators/window_animator_vtranslate.c \
src/awtk/src/window_manager/window_manager_default.c \
src/awtk/src/window_manager/window_manager_simple.c \
src/awtk/src/xml/xml_builder.c \
src/awtk/src/xml/xml_parser.c \
src/awtk/tests/action_queue_test.cc \
src/awtk/tests/action_thread_pool_test.cpp \
src/awtk/tests/action_thread_test.cpp \
src/awtk/tests/animator_move_test.cc \
src/awtk/tests/animator_opacity_test.cc \
src/awtk/tests/animator_rotation_test.cc \
src/awtk/tests/animator_scale_test.cc \
src/awtk/tests/animator_value_test.cc \
src/awtk/tests/app_bar_test.cc \
src/awtk/tests/assets_manager_test.cc \
src/awtk/tests/asset_loader_zip_test.cc \
src/awtk/tests/basic_test.cc \
src/awtk/tests/bitmap_test.cc \
src/awtk/tests/blend_image_test.cc \
src/awtk/tests/buffer_test.cc \
src/awtk/tests/button_test.cc \
src/awtk/tests/calibration_win_test.cc \
src/awtk/tests/candidates_test.cc \
src/awtk/tests/canvas_test.cc \
src/awtk/tests/canvas_widget_test.cc \
src/awtk/tests/check_button_test.cc \
src/awtk/tests/children_layouter_default_test.cc \
src/awtk/tests/children_layouter_factory_test.cc \
src/awtk/tests/children_layouter_list_view_test.cc \
src/awtk/tests/clip_board_test.cc \
src/awtk/tests/clip_view_test.cc \
src/awtk/tests/color_component_test.cc \
src/awtk/tests/color_parser_test.cc \
src/awtk/tests/color_picker_test.cc \
src/awtk/tests/color_test.cc \
src/awtk/tests/color_tile_test.cc \
src/awtk/tests/column_test.cc \
src/awtk/tests/combo_box_ex_test.cc \
src/awtk/tests/combo_box_item_test.cc \
src/awtk/tests/combo_box_test.cc \
src/awtk/tests/common.cc \
src/awtk/tests/compressor_test.cc \
src/awtk/tests/cond_var.cc \
src/awtk/tests/copy_image_test.cc \
src/awtk/tests/darray_test.cc \
src/awtk/tests/data_reader_factory_test.cc \
src/awtk/tests/data_writer_factory_test.cc \
src/awtk/tests/date_time_format_test.cc \
src/awtk/tests/dialog_client_test.cc \
src/awtk/tests/dialog_highlighter_test.cc \
src/awtk/tests/dialog_test.cc \
src/awtk/tests/dialog_title_test.cc \
src/awtk/tests/digit_clock_test.cc \
src/awtk/tests/draggable_test.cc \
src/awtk/tests/dragger_test.cc \
src/awtk/tests/edit_test.cc \
src/awtk/tests/emitter_test.cc \
src/awtk/tests/endian_test.cc \
src/awtk/tests/enums_test.cc \
src/awtk/tests/events_test.cc \
src/awtk/tests/event_queue_test.cc \
src/awtk/tests/event_source_fd_test.cc \
src/awtk/tests/event_source_idle_test.cc \
src/awtk/tests/event_source_manager_test.cc \
src/awtk/tests/event_source_timer_test.cc \
src/awtk/tests/expr_test.cc \
src/awtk/tests/file_browser_test.cc \
src/awtk/tests/fill_image_test.cc \
src/awtk/tests/font_dummy.c \
src/awtk/tests/font_gen_test.cc \
src/awtk/tests/font_manager_test.cc \
src/awtk/tests/fragment_frame_buffer_test.cc \
src/awtk/tests/fs_test.cc \
src/awtk/tests/func_call_parser_test.cc \
src/awtk/tests/gif_image_test.cc \
src/awtk/tests/glyph_cache_test.cc \
src/awtk/tests/grid_item_test.cc \
src/awtk/tests/grid_test.cc \
src/awtk/tests/group_box_test.cc \
src/awtk/tests/guage_pointer_test.cc \
src/awtk/tests/guage_test.cc \
src/awtk/tests/hscroll_label_test.cc \
src/awtk/tests/idle_test.cc \
src/awtk/tests/image_animation_test.cc \
src/awtk/tests/image_loader_stb_test.cc \
src/awtk/tests/image_manager_test.cc \
src/awtk/tests/image_test.cc \
src/awtk/tests/image_value_test.cc \
src/awtk/tests/input_device_status_test.cc \
src/awtk/tests/int_str_test.cc \
src/awtk/tests/iostream_noisy_test.cc \
src/awtk/tests/iostream_shdlc_test.cc \
src/awtk/tests/istream_buffered_test.cc \
src/awtk/tests/istream_mem_test.cc \
src/awtk/tests/keyboard_test.cc \
src/awtk/tests/label_test.cc \
src/awtk/tests/lcd_log.cc \
src/awtk/tests/lcd_mem_test.cc \
src/awtk/tests/lcd_mono_test.cc \
src/awtk/tests/line_break_test.cc \
src/awtk/tests/list_item_test.cc \
src/awtk/tests/list_view_h_test.cc \
src/awtk/tests/list_view_test.cc \
src/awtk/tests/locale_test.cc \
src/awtk/tests/main.cc \
src/awtk/tests/matrix_test.cc \
src/awtk/tests/mem_test.cpp \
src/awtk/tests/mledit_test.cc \
src/awtk/tests/mutable_image_test.cc \
src/awtk/tests/mutex_test.cc \
src/awtk/tests/named_value_test.cc \
src/awtk/tests/object_array_test.cc \
src/awtk/tests/object_default_test.cc \
src/awtk/tests/ostream_buffered_test.cc \
src/awtk/tests/ostream_mem_test.cc \
src/awtk/tests/ostream_retry_test.cc \
src/awtk/tests/pages_test.cc \
src/awtk/tests/path_test.cc \
src/awtk/tests/pixel_test.cc \
src/awtk/tests/popup_test.cc \
src/awtk/tests/progress_bar_test.cc \
src/awtk/tests/progress_circle_test.cc \
src/awtk/tests/rect_test.cc \
src/awtk/tests/recycle_test.cpp \
src/awtk/tests/rich_text_node_test.cc \
src/awtk/tests/rich_text_parser_test.cc \
src/awtk/tests/rich_text_render_node_test.cc \
src/awtk/tests/rich_text_test.cc \
src/awtk/tests/ring_buffer_test.cc \
src/awtk/tests/rom_fs_test.cc \
src/awtk/tests/rotate_image_test.cc \
src/awtk/tests/row_test.cc \
src/awtk/tests/scroll_bar_test.cc \
src/awtk/tests/scroll_view_test.cc \
src/awtk/tests/self_layouter_default_test.cc \
src/awtk/tests/self_layouter_factory_test.cc \
src/awtk/tests/self_layouter_menu_test.cc \
src/awtk/tests/semaphore_test.cc \
src/awtk/tests/shdlc_test.cc \
src/awtk/tests/shortcut_test.cc \
src/awtk/tests/slider_test.cc \
src/awtk/tests/slide_menu_test.cc \
src/awtk/tests/slide_view_test.cc \
src/awtk/tests/slist_test.cc \
src/awtk/tests/soft_g2d_test.cc \
src/awtk/tests/spin_box_test.cc \
src/awtk/tests/stream_file_test.cc \
src/awtk/tests/str_gen_test.cc \
src/awtk/tests/str_str_test.cc \
src/awtk/tests/str_test.cc \
src/awtk/tests/style_const_test.cc \
src/awtk/tests/style_mutable_test.cc \
src/awtk/tests/style_test.cc \
src/awtk/tests/suggest_test.cc \
src/awtk/tests/svg_image_test.cc \
src/awtk/tests/svg_test.cc \
src/awtk/tests/svg_to_bsvg_test.cc \
src/awtk/tests/switch_test.cc \
src/awtk/tests/system_bar_test.cc \
src/awtk/tests/system_info_test.cc \
src/awtk/tests/tab_button_group_test.cc \
src/awtk/tests/tab_button_test.cc \
src/awtk/tests/tab_control_test.cc \
src/awtk/tests/text_edit_test.cc \
src/awtk/tests/text_selector_test.cc \
src/awtk/tests/theme_gen_test.cc \
src/awtk/tests/theme_test.cc \
src/awtk/tests/timer_info_test.cc \
src/awtk/tests/timer_test.cc \
src/awtk/tests/time_clock_test.cc \
src/awtk/tests/tokenizer_test.cc \
src/awtk/tests/ubjson_parser_test.cc \
src/awtk/tests/ubjson_reader_test.cc \
src/awtk/tests/ubjson_writer_test.cc \
src/awtk/tests/ui_loader_default_test.cc \
src/awtk/tests/ui_loader_xml_test.cc \
src/awtk/tests/ui_serializer_test.cc \
src/awtk/tests/ui_xml_writer_test.cc \
src/awtk/tests/utf8_test.cc \
src/awtk/tests/utils_test.cc \
src/awtk/tests/value_desc_test.cc \
src/awtk/tests/value_test.cc \
src/awtk/tests/velocity_test.cc \
src/awtk/tests/view_test.cc \
src/awtk/tests/waitable_action_queue_test.cpp \
src/awtk/tests/widget_animator_factory_test.cc \
src/awtk/tests/widget_animator_manager_test.cc \
src/awtk/tests/widget_factory_test.cc \
src/awtk/tests/widget_test.cc \
src/awtk/tests/window_design.c \
src/awtk/tests/window_design_test.cc \
src/awtk/tests/window_test.cc \
src/awtk/tests/wstr_test.cc \
src/awtk/tests/xml_parser_test.cc \
src/awtk/tools/common/utils.c \
src/awtk/tools/font_gen/font_gen.c \
src/awtk/tools/font_gen/gen_ascii.c \
src/awtk/tools/font_gen/main.c \
src/awtk/tools/image_gen/image_gen.c \
src/awtk/tools/image_gen/main.c \
src/awtk/tools/image_resize/info.c \
src/awtk/tools/image_resize/resize.c \
src/awtk/tools/image_resize/to_rgb565.c \
src/awtk/tools/res_gen/main.c \
src/awtk/tools/str_gen/main.cc \
src/awtk/tools/str_gen/str_gen.cc \
src/awtk/tools/str_gen/xml_str_gen.cc \
src/awtk/tools/svg_gen/bsvg_dump.cc \
src/awtk/tools/svg_gen/bsvg_gen.cc \
src/awtk/tools/theme_gen/main.cc \
src/awtk/tools/theme_gen/theme_gen.cc \
src/awtk/tools/theme_gen/xml_theme_gen.cc \
src/awtk/tools/ui_gen/qt_to_xml/qt_to_xml.cc \
src/awtk/tools/ui_gen/rc_to_xml/rc_to_xml.cc \
src/awtk/tools/ui_gen/xml_to_ui/xml_to_ui.c \
src/awtk_platform_msrtos.c

#*********************************************************************************************************
# Header file search path (eg. LOCAL_INC_PATH := -I"Your hearder files search path")
#*********************************************************************************************************
LOCAL_INC_PATH := \
-I"./src" \
-I"./src/awtk" \
-I"./src/awtk/3rd" \
-I"./src/awtk/src" \
-I"./src/awtk/src/ext_widgets" \
-I"./src/awtk/3rd/agge" \
-I"./src/awtk/3rd/libunibreak" \
-I"./src/awtk/3rd/stb" \
-I"./src/awtk/3rd/nanovg" \
-I"./src/awtk/3rd/nanovg/base"

#*********************************************************************************************************
# Pre-defined macro (eg. -DYOUR_MARCO=1)
#*********************************************************************************************************
LOCAL_DSYMBOL := \
-DHAS_AWTK_CONFIG=1

#*********************************************************************************************************
# Depend library (eg. LOCAL_DEPEND_LIB := -la LOCAL_DEPEND_LIB_PATH := -L"Your library search path")
#*********************************************************************************************************
LOCAL_DEPEND_LIB      := 
LOCAL_DEPEND_LIB_PATH := 

#*********************************************************************************************************
# C++ config
#*********************************************************************************************************
LOCAL_USE_CXX        := no
LOCAL_USE_CXX_EXCEPT := no

#*********************************************************************************************************
# Code coverage config
#*********************************************************************************************************
LOCAL_USE_GCOV := no

include $(STATIC_LIBRARY_MK)

#*********************************************************************************************************
# End
#*********************************************************************************************************
